"""
Type system for Foobara Python.

Provides:
- Ruby-compatible type declarations with processors
- Type registry for type lookup
- Built-in casters, validators, and transformers
- Sensitive data handling
"""

from foobara_py.types.sensitive import (
    APIKey,
    BearerToken,
    Password,
    SecretToken,
    Sensitive,
    SensitiveModel,
    SensitiveStr,
    get_sensitive_fields,
    is_sensitive,
    redact_dict,
)

from foobara_py.types.type_declarations import (
    # Protocols
    ProcessorProtocol,
    # Core classes
    FoobaraType,
    TypeRegistry,
    TypeProcessor,
    Caster,
    Validator,
    Transformer,
    # Built-in casters
    StringCaster,
    IntegerCaster,
    FloatCaster,
    BooleanCaster,
    DateCaster,
    DateTimeCaster,
    UUIDCaster,
    ListCaster,
    DictCaster,
    # Built-in validators
    RequiredValidator,
    MinLengthValidator,
    MaxLengthValidator,
    MinValueValidator,
    MaxValueValidator,
    PatternValidator,
    OneOfValidator,
    EmailValidator,
    URLValidator,
    RangeValidator,
    NotEmptyValidator,
    UniqueItemsValidator,
    ContainsValidator,
    # Built-in transformers
    StripWhitespaceTransformer,
    LowercaseTransformer,
    UppercaseTransformer,
    TitleCaseTransformer,
    RoundTransformer,
    ClampTransformer,
    DefaultTransformer,
    TruncateTransformer,
    SlugifyTransformer,
    NormalizeWhitespaceTransformer,
    # Built-in types
    StringType,
    IntegerType,
    FloatType,
    BooleanType,
    DateType,
    DateTimeType,
    UUIDType,
    EmailType,
    URLType,
    PositiveIntegerType,
    NonNegativeIntegerType,
    PercentageType,
    ArrayType,
    HashType,
    # DSL functions
    type_declaration,
    define_type,
)

from foobara_py.types.base import (
    EmailAddress,
    LongStr,
    LowercaseStr,
    MediumStr,
    NonEmptyStr,
    NonNegativeFloat,
    NonNegativeInt,
    Percentage,
    PhoneNumber,
    PositiveFloat,
    PositiveInt,
    ShortStr,
    TitleCaseStr,
    Username,
    string_length,
)

__all__ = [
    # Sensitive types
    "Sensitive",
    "SensitiveStr",
    "Password",
    "APIKey",
    "SecretToken",
    "BearerToken",
    "SensitiveModel",
    "is_sensitive",
    "get_sensitive_fields",
    "redact_dict",
    # Protocols
    "ProcessorProtocol",
    # Core type system
    "FoobaraType",
    "TypeRegistry",
    "TypeProcessor",
    "Caster",
    "Validator",
    "Transformer",
    # Built-in casters
    "StringCaster",
    "IntegerCaster",
    "FloatCaster",
    "BooleanCaster",
    "DateCaster",
    "DateTimeCaster",
    "UUIDCaster",
    "ListCaster",
    "DictCaster",
    # Built-in validators
    "RequiredValidator",
    "MinLengthValidator",
    "MaxLengthValidator",
    "MinValueValidator",
    "MaxValueValidator",
    "PatternValidator",
    "OneOfValidator",
    "EmailValidator",
    "URLValidator",
    "RangeValidator",
    "NotEmptyValidator",
    "UniqueItemsValidator",
    "ContainsValidator",
    # Built-in transformers
    "StripWhitespaceTransformer",
    "LowercaseTransformer",
    "UppercaseTransformer",
    "TitleCaseTransformer",
    "RoundTransformer",
    "ClampTransformer",
    "DefaultTransformer",
    "TruncateTransformer",
    "SlugifyTransformer",
    "NormalizeWhitespaceTransformer",
    # Built-in types
    "StringType",
    "IntegerType",
    "FloatType",
    "BooleanType",
    "DateType",
    "DateTimeType",
    "UUIDType",
    "EmailType",
    "URLType",
    "PositiveIntegerType",
    "NonNegativeIntegerType",
    "PercentageType",
    "ArrayType",
    "HashType",
    # DSL
    "type_declaration",
    "define_type",
    # Pydantic type aliases
    "EmailAddress",
    "LongStr",
    "LowercaseStr",
    "MediumStr",
    "NonEmptyStr",
    "NonNegativeFloat",
    "NonNegativeInt",
    "Percentage",
    "PhoneNumber",
    "PositiveFloat",
    "PositiveInt",
    "ShortStr",
    "TitleCaseStr",
    "Username",
    "string_length",
]
